import type { Metadata } from "next";
import "./globals.css";
import connectDb from "../db/db";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

void connectDb()

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
